const books = [
  {
    id: 1,
    title: "A Hipótese do Amor",
    author: "Ali Hazelwood",
    price: "42,22",
    discount: "10%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81jsEgM0apL.jpg",
    synopsis: "Quando um relacionamento falso entre cientistas encontra a irresistível força da atração, as teorias de uma mulher sobre o amor, cuidadosamente calculadas, são postas à prova.",
    comments: 20,
    editor: "Editora",
    details: "março de 2022"
  },
  {
    id: 2,
    title: "Uma Farsa de Amor",
    author: "Elena Armas",
    price: "46,00",
    discount: "15%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81H38n6Vd-L.jpg",
    synopsis: "Catalina precisa de um acompanhante para um casamento na Espanha e inventa um namoro falso. O plano começa a sair do controle quando os sentimentos aparecem.",
    comments: 25,
    editor: "Arqueiro",
    details: "agosto de 2022"
  },
  {
    id: 3,
    title: "Melhor do Que nos Filmes",
    author: "Lynn Painter",
    price: "38,99",
    discount: "12%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/71n0dN0lW5L.jpg",
    synopsis: "Liz sempre sonhou com um romance digno de cinema, mas acaba descobrindo que o amor pode ser ainda melhor do que nos filmes.",
    comments: 20,
    editor: "Intrínseca",
    details: "março de 2022"
  },
  {
    id: 4,
    title: "Sorte no Amor",
    author: "Lynn Painter",
    price: "41,22",
    discount: "12%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81p5cB1Q4lL.jpg",
    synopsis: "Hallie tenta recomeçar e acaba encontrando Jack. Entre provocação e química, os dois embarcam em uma aposta perigosa sobre o amor.",
    comments: 20,
    editor: "Intrínseca",
    details: "março de 2022"
  },
  {
    id: 5,
    title: "A Cinco Passos de Você",
    author: "Rachel Lippincott",
    price: "45,32",
    discount: "25%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81vpsIs58WL.jpg",
    synopsis: "Dois jovens que convivem com fibrose cística se apaixonam, mas precisam manter distância um do outro.",
    comments: 26,
    editor: "Alt",
    details: "março de 2022"
  },
  {
    id: 6,
    title: "Até o Verão Terminar",
    author: "Colleen Hoover",
    price: "44,90",
    discount: "15%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81uX0pG7FDL.jpg",
    synopsis: "Beyah tenta sobreviver ao passado e encontra no verão e em um novo vizinho uma chance inesperada de recomeçar.",
    comments: 20,
    editor: "Galera",
    details: "março de 2022"
  },
  {
    id: 7,
    title: "O Beijo da Neve",
    author: "Babi A. Sette",
    price: "39,99",
    discount: "9%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81P4zN5hGDL.jpg",
    synopsis: "Nina tenta voltar à sua vida e à patinação, mas reencontra Elyan e precisa lidar com sentimentos do passado.",
    comments: 20,
    editor: "Versus",
    details: "março de 2022"
  },
  {
    id: 8,
    title: "Amor e Gelato",
    author: "Jenna Evans Welch",
    price: "40,73",
    discount: "13%",
    category: "romance",
    image: "https://m.media-amazon.com/images/I/81KhQfQMPUL.jpg",
    synopsis: "Depois da morte da mãe, Lina vai para a Itália e acaba encontrando romance, segredos de família e novas descobertas sobre si mesma.",
    comments: 20,
    editor: "Intrínseca",
    details: "março de 2022"
  },
  {
    id: 9,
    title: "Quarta Asa",
    author: "Rebecca Yarros",
    price: "67,00",
    discount: "11%",
    category: "fantasia",
    image: "https://m.media-amazon.com/images/I/81-1h6r7XVL.jpg",
    synopsis: "Violet entra em uma academia militar brutal onde precisa sobreviver e provar sua força em meio a dragões, guerra e rivalidades.",
    comments: 20,
    editor: "Planeta",
    details: "março de 2022"
  },
  {
    id: 10,
    title: "O Rei Perverso",
    author: "Holly Black",
    price: "41,32",
    discount: "14%",
    category: "fantasia",
    image: "https://m.media-amazon.com/images/I/81LgB6M2WlL.jpg",
    synopsis: "Jude está cada vez mais envolvida em intrigas e disputas perigosas no mundo das fadas, onde o poder cobra um preço alto.",
    comments: 20,
    editor: "Galera",
    details: "março de 2022"
  },
  {
    id: 11,
    title: "De Sangue e Cinzas",
    author: "Jennifer L. Armentrout",
    price: "64,22",
    discount: "27%",
    category: "fantasia",
    image: "https://m.media-amazon.com/images/I/81mQ7Q0g6oL.jpg",
    synopsis: "Poppy foi escolhida para uma vida sagrada, mas seu destino pode mudar completamente quando segredos e perigos começam a cercá-la.",
    comments: 20,
    editor: "Galera",
    details: "março de 2022"
  },
  {
    id: 12,
    title: "Sombra e Ossos",
    author: "Leigh Bardugo",
    price: "45,99",
    discount: "18%",
    category: "fantasia",
    image: "https://m.media-amazon.com/images/I/81Q6D0qS6jL.jpg",
    synopsis: "Alina descobre um poder raro e precisa enfrentar forças sombrias que ameaçam todo o seu mundo.",
    comments: 20,
    editor: "Planeta",
    details: "março de 2022"
  },
  {
    id: 13,
    title: "Alice no País das Maravilhas",
    author: "Lewis Carroll",
    price: "48,99",
    discount: "17%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/81i3jFJ5GLL.jpg",
    synopsis: "Alice cai em um mundo fantástico cheio de criaturas estranhas e desafios inesperados.",
    comments: 20,
    editor: "Zahar",
    details: "março de 2022"
  },
  {
    id: 14,
    title: "A Rainha Vermelha",
    author: "Victoria Aveyard",
    price: "45,95",
    discount: "15%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/81lKvgzab-L.jpg",
    synopsis: "Em um reino dividido pelo sangue, Mare descobre poderes que podem mudar tudo.",
    comments: 20,
    editor: "Seguinte",
    details: "março de 2022"
  },
  {
    id: 15,
    title: "A Biblioteca da Meia-Noite",
    author: "Matt Haig",
    price: "45,32",
    discount: "10%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/81J6APjwxlL.jpg",
    synopsis: "Entre a vida e a morte, Nora encontra uma biblioteca que mostra caminhos alternativos para sua existência.",
    comments: 21,
    editor: "Bertrand",
    details: "2021"
  },
  {
    id: 16,
    title: "Orgulho e Preconceito",
    author: "Jane Austen",
    price: "41,22",
    discount: "11%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/91hhCXjP8IL.jpg",
    synopsis: "Elizabeth Bennet conhece o reservado Sr. Darcy e, entre desencontros e julgamentos, nasce uma das histórias mais clássicas da literatura.",
    comments: 20,
    editor: "Martin Claret",
    details: "março de 2022"
  },
  {
    id: 17,
    title: "Harry Potter e A Ordem Da Fenix",
    author: "J. K. Rowling",
    price: "69,00",
    discount: "17%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/81ibfYk4qmL.jpg",
    synopsis: "Harry retorna a Hogwarts e encontra um mundo mais sombrio, cheio de conflitos e mistérios.",
    comments: 20,
    editor: "Rocco",
    details: "março de 2022"
  },
  {
    id: 18,
    title: "O Menino do Pijama Listrado",
    author: "John Boyne",
    price: "45,90",
    discount: "13%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/91K0bJ7X4GL.jpg",
    synopsis: "Bruno conhece Shmuel e, em meio à guerra, nasce uma amizade inocente e profundamente marcante.",
    comments: 20,
    editor: "Seguinte",
    details: "março de 2022"
  },
  {
    id: 19,
    title: "O Hobbit",
    author: "J. R. R. Tolkien",
    price: "34,90",
    discount: "10%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/91b0C2YNSrL.jpg",
    synopsis: "Bilbo Bolseiro parte em uma jornada inesperada com anões e um mago rumo à Montanha Solitária.",
    comments: 20,
    editor: "HarperCollins",
    details: "março de 2022"
  },
  {
    id: 20,
    title: "Percy Jackson e Os Olimpianos",
    author: "Rick Riordan",
    price: "35,22",
    discount: "10%",
    category: "aventura",
    image: "https://m.media-amazon.com/images/I/91a1ByKhm-L.jpg",
    synopsis: "Percy embarca numa jornada mitológica para impedir uma guerra entre os deuses.",
    comments: 20,
    editor: "Intrínseca",
    details: "março de 2022"
  }
];